# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cu_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 700))
        MainWindow.setMaximumSize(QtCore.QSize(640, 700))
        MainWindow.setStyleSheet("background-color: #111933;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #087cc0;")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.task_name_field = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.task_name_field.setFont(font)
        self.task_name_field.setStyleSheet("QLineEdit{\n"
"\n"
"    border: 2px solid #087cc0;\n"
"    color: #087cc0;\n"
"    font: 75 14pt \"Book Antiqua\";\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(25, 38, 76);\n"
"}\n"
"\n"
"")
        self.task_name_field.setObjectName("task_name_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.task_name_field)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #087cc0;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.task_description_field = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.task_description_field.setStyleSheet("QPlainTextEdit{\n"
"\n"
"    border: 2px solid #087cc0;\n"
"    color: #087cc0;\n"
"    font: 75 14pt \"Book Antiqua\";\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover{\n"
"    background-color: rgb(25, 38, 76);\n"
"}\n"
"\n"
"")
        self.task_description_field.setObjectName("task_description_field")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.task_description_field)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #087cc0;")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.expiration_date_spinner = QtWidgets.QDateEdit(self.centralwidget)
        self.expiration_date_spinner.setStyleSheet("QDateEdit{\n"
"\n"
"    border: 2px solid #087cc0;\n"
"    color: #087cc0;\n"
"    font: 75 14pt \"Book Antiqua\";\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QDateEdit:hover{\n"
"    background-color: rgb(25, 38, 76);\n"
"}\n"
"\n"
"")
        self.expiration_date_spinner.setAlignment(QtCore.Qt.AlignCenter)
        self.expiration_date_spinner.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expiration_date_spinner.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.expiration_date_spinner.setCalendarPopup(False)
        self.expiration_date_spinner.setObjectName("expiration_date_spinner")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.expiration_date_spinner)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #087cc0;")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.task_status_list = QtWidgets.QListWidget(self.centralwidget)
        self.task_status_list.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.task_status_list.setFont(font)
        self.task_status_list.setStyleSheet("QListWidget{\n"
"    background-color: #087cc0;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QListWidget::item{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #087cc0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget::item:hover{\n"
"    background-color: #0d4273;\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background-color: #0d4273;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    border: none;\n"
"    background:#087cc0;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #0d5377;\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#03d3f2;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #03d3f2;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.task_status_list.setObjectName("task_status_list")
        item = QtWidgets.QListWidgetItem()
        self.task_status_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.task_status_list.addItem(item)
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.task_status_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_changes_Btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_changes_Btn.sizePolicy().hasHeightForWidth())
        self.save_changes_Btn.setSizePolicy(sizePolicy)
        self.save_changes_Btn.setMinimumSize(QtCore.QSize(80, 40))
        self.save_changes_Btn.setStyleSheet("QPushButton{\n"
"\n"
"    border: 2px solid #087cc0;\n"
"    color: #087cc0;\n"
"    font: 75 14pt \"Book Antiqua\";\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(25, 38, 76);\n"
"}\n"
"\n"
"")
        self.save_changes_Btn.setObjectName("save_changes_Btn")
        self.horizontalLayout.addWidget(self.save_changes_Btn)
        self.discard_changes_Btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discard_changes_Btn.sizePolicy().hasHeightForWidth())
        self.discard_changes_Btn.setSizePolicy(sizePolicy)
        self.discard_changes_Btn.setMinimumSize(QtCore.QSize(80, 40))
        self.discard_changes_Btn.setStyleSheet("QPushButton{\n"
"\n"
"    border: 2px solid #087cc0;\n"
"    color: #087cc0;\n"
"    font: 75 14pt \"Book Antiqua\";\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(25, 38, 76);\n"
"}\n"
"\n"
"")
        self.discard_changes_Btn.setObjectName("discard_changes_Btn")
        self.horizontalLayout.addWidget(self.discard_changes_Btn)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Task name:"))
        self.label_2.setText(_translate("MainWindow", "Task description (optional):"))
        self.label_3.setText(_translate("MainWindow", "Expiration date: "))
        self.label_4.setText(_translate("MainWindow", "Status: "))
        __sortingEnabled = self.task_status_list.isSortingEnabled()
        self.task_status_list.setSortingEnabled(False)
        item = self.task_status_list.item(0)
        item.setText(_translate("MainWindow", "Uncomplete"))
        item = self.task_status_list.item(1)
        item.setText(_translate("MainWindow", "Complete"))
        self.task_status_list.setSortingEnabled(__sortingEnabled)
        self.save_changes_Btn.setText(_translate("MainWindow", "OK"))
        self.discard_changes_Btn.setText(_translate("MainWindow", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
